### ISSUE TITLE
Shader issue on macOS

### ISSUE THREAD

**Issue by EtherTyper** [Novum/vkQuake#491]
I'm getting the following issue after compiling and running on macOS:

```
Command line: ./vkquake -basedir /Users/ethertyper/Downloads/QuakePAKs/
Found SDL version 2.0.22
Detected 8 CPUs.
Built with Clang 13.1.6 (clang-1316.0.21.2.5)
Quake 1.09 (c) id Software
GLQuake 1.00 (c) id Software
FitzQuake 0.85 (c) John Fitzgibbons
FitzQuake SDL port (c) SleepwalkR, Baker
QuakeSpasm 0.94.5 (c) Ozkan Sezer, Eric Wasylishen & others
QuakeSpasm-Spiked (c) Spike
vkQuake 1.20.0 (c) Axel Gneiting & others
Host_Init
Playing registered version.
Console initialized.
UDP_Init: skipping gethostbyname for Elis-MacBook-Pro.local
UDP4 Initialized
UDPv6 Initialized
Server using protocol 999+ (FTE-RMQ)
Exe: 02:27:02 Jun 24 2022
384.0 megabyte heap

Vulkan Initialization
Using Vulkan 1.1
[mvk-info] MoltenVK version 1.1.10, supporting Vulkan version 1.1.216.
	The following 78 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_surface v1
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_swapchain_colorspace v4
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v34
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] GPU device:
		model: Intel(R) Iris(TM) Plus Graphics 655
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x3ea5
		pipelineCacheUUID: 0000277E-0C03-07D2-0000-000000000000
	supports the following Metal Versions, GPU's and Feature Sets:
		Metal Shading Language 2.4
		GPU Family Mac 2
		GPU Family Mac 1
		GPU Family Common 3
		GPU Family Common 2
		GPU Family Common 1
		macOS GPU Family 2 v1
		macOS GPU Family 1 v4
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 4 Vulkan extensions enabled:
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_surface v25
		VK_MVK_macos_surface v3
Using VK_KHR_surface
Using VK_MVK_macos_surface
Using VK_KHR_get_surface_capabilities2
Using VK_KHR_get_physical_device_properties2
Vendor: Intel
Device: Intel(R) Iris(TM) Plus Graphics 655
Using subgroup operations
[mvk-info] Using MTLEvent for Vulkan semaphores.
[mvk-info] Created VkDevice to run on GPU Intel(R) Iris(TM) Plus Graphics 655 with the following 4 Vulkan extensions enabled:
		VK_KHR_dedicated_allocation v3
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_swapchain v70
		VK_EXT_subgroup_size_control v2
Using VK_KHR_swapchain
Using VK_KHR_get_memory_requirements2
Using VK_KHR_dedicated_allocation
Using VK_EXT_subgroup_size_control
Using A2B10G10R10 color buffer format
Using D32_S8 depth buffer format
Creating command buffers
Initializing staging
Creating descriptor set layouts
Reallocating dynamic VBs (256 KB)
Reallocating dynamic IBs (1024 KB)
Reallocating dynamic UBs (256 KB)
Initializing samplers
Texture lod bias: 0.000000
Creating pipeline layouts
Using IMMEDIATE present mode
[mvk-info] Created 2 swapchain images with initial size (1440, 736).
Creating color buffer
AA disabled
Creating depth buffer
Creating render passes
Creating frame buffers
Creating pipelines
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:106:16: error: use of undeclared identifier '_349'; did you mean '_363'?
        _363 = _349;
               ^~~~
               _363
program_source:45:12: note: '_363' declared here
    float4 _363;
           ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.

ERROR-OUT BEGIN


QUAKE ERROR: vkCreateComputePipelines failed
```

Using git bisect, I found the issue was introduced in cdbc580285220535e5add3944a30aca04dc9af84 and b5151026846516ccf958cf618d50b4b35d9a92de, as the program fails to run due to shader issues on cdbc580285220535e5add3944a30aca04dc9af84 but runs properly on de692b2df1bd909502a65ce47d89a0d92062eb83.

**Comment by Novum** [comment]
This is a MoltenVK issue. I do not have a mac and I'm not interested to work around their bugs.

**Comment by Novum** [comment]
Just to be clear, if you want to have this fixed you should file a bug here https://github.com/KhronosGroup/MoltenVK/issues

This is not a bug in my code, I can't help you.

**Comment by lemonzest79** [comment]
I'm having shader issues on Linux also, (vkQuake 1.20.0 win64 build in wine) and it looks all strange

![Screenshot from 2022-06-28 18-50-42](https://user-images.githubusercontent.com/40669977/176251339-76b25825-bcc0-4108-af2c-a3c3659c9972.png)

GPU is a AMD Radeon RX 6600 XT with Mesa drivers 21.3.8 (RADV vulkan driver) on fedora 36

**Comment by j4reporting** [comment]
is there a specific reason for using the windows binary with WINE instead the linux binary?   Works for me  on fedora 36  with nvidia gpu and wayland.  It has some issue (core dump) on quit, but this looks more like a wayland issue.

**Comment by Novum** [comment]
> is there a specific reason for using the windows binary with WINE instead the linux binary? Works for me on fedora 36 with nvidia gpu and wayland. It has some issue (core dump) on quit, but this looks more like a wayland issue.

This shouldn't make a difference, shaders are the same.

**Comment by Novum** [comment]
I recompiled the shaders with a newer glslang version, maybe that somehow fixed this issue

**Comment by alexey-lysiuk** [comment]
No, error is mostly the same.
```
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:106:16: error: use of undeclared identifier '_350'; did you mean '_354'?
        _364 = _350;
               ^~~~
               _354
program_source:54:16: note: '_354' declared here
        float4 _354;
               ^
.
[mvk-error] VK_ERROR_INVALID_SHADER_NV: Compute shader function could not be compiled into pipeline. See previous logged error.
```

Setting `MVK_DEBUG` environment variable to `1` gives the following output.
```
Converted MSL:
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct _35
{
    uint2 _m0;
    float2 _m1;
    float _m2;
    float _m3;
    uint _m4;
    float _m5;
    float _m6;
    float _m7;
    float _m8;
};

struct _183
{
    uint4 _m0[2];
};

struct _186
{
    _183 _m0[184];
};

constant uint3 gl_WorkGroupSize [[maybe_unused]] = uint3(8u, 8u, 1u);

kernel void main0(constant _35& _37 [[buffer(0)]], constant _186& _188 [[buffer(2)]], texture2d<float> _111 [[texture(0)]], texture2d<float, access::write> _304 [[texture(1)]], texture_buffer<float> _242 [[texture(2)]], sampler _111Smplr [[sampler(0)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    float4 _361;
    if ((_37._m4 & 1u) != 0u)
    {
        float _60 = 0.0033333334140479564666748046875 * _37._m2;
        float _63 = float(gl_GlobalInvocationID.x);
        float _70 = float(gl_GlobalInvocationID.y);
        _361 = _111.sample(_111Smplr, float2(fma(fma(_63, _37._m1.x, sin(fma(_70 * _37._m1.y, 15.70794963836669921875, _37._m3)) * 0.0033333334140479564666748046875), 0.993333339691162109375, 0.0033333334140479564666748046875), fma(fma(_70, _37._m1.y, sin(fma(_63 * _37._m1.x, 15.70794963836669921875 * _37._m2, _37._m3)) * _60), fma(-_37._m2, 0.006666666828095912933349609375, 1.0), _60)), level(0.0));
    }
    else
    {
        _361 = _111.read(uint2(int2(int(min(_37._m0.x, gl_GlobalInvocationID.x)), int(min(_37._m0.y, gl_GlobalInvocationID.y)))), 0);
    }
    float4 _364;
    if ((_37._m4 & 16u) != 0u)
    {
        uint3 _148 = uint3(_361.xyz * 255.0);
        uint3 _315;
        _315 = uint3(0u);
        uint _196;
        uint3 _208;
        uint _210;
        float4 _354;
        uint _316 = 7u;
        uint _317 = 0u;
        for (;;)
        {
            uint3 _165 = uint3(_316);
            uint3 _166 = (_148 - _315) >> _165;
            uint _179 = (_166.x + (_166.y * 2u)) + (_166.z * 4u);
            _196 = _188._m0[_317]._m0[_179 / 4u][_179 % 4u];
            if (!((_196 & 2147483648u) == 0u))
            {
                uint _216 = _196 & 15u;
                uint _221 = (_196 >> uint(4)) & 65535u;
                int _318;
                float3 _320;
                float _330;
                _330 = 9.9999996802856924650656260769173e+37;
                _320 = float3(0.0);
                _318 = 0;
                uint _235;
                for (;;)
                {
                    _235 = uint(_318);
                    if (_235 < _216)
                    {
                        float3 _251 = _242.read(uint(int(_221 + _235))).xyz;
                        float3 _256 = _361.xyz - _251;
                        float _261 = dot(_256, _256);
                        bool _264 = _261 < _330;
                        _330 = _264 ? _261 : _330;
                        _320 = select(_320, _251, bool3(_264));
                        _318++;
                        continue;
                    }
                    else
                    {
                        break;
                    }
                }
                float4 _350 = _361;
                _350.x = _320.x;
                _350.y = _320.y;
                _350.z = _320.z;
                break;
            }
            _208 = _315 + (_166 << _165);
            _210 = _316 - 1u;
            _317 = _196;
            _316 = _210;
            _315 = _208;
            continue;
        }
        _364 = _350;
    }
    else
    {
        _364 = _361;
    }
    float3 _295 = mix(_364.xyz, float3(_37._m5, _37._m6, _37._m7), float3(_37._m8));
    float4 _356 = _364;
    _356.x = _295.x;
    _356.y = _295.y;
    _356.z = _295.z;
    _304.write(_356, uint2(int2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y))));
}

End MSL

Estimated original GLSL:
#version 450
layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

struct _183
{
    uvec4 _m0[2];
};

layout(set = 0, binding = 3, std140) uniform _186_188
{
    _183 _m0[184];
} _188;

layout(push_constant, std430) uniform _35_37
{
    uvec2 _m0;
    vec2 _m1;
    float _m2;
    float _m3;
    uint _m4;
    float _m5;
    float _m6;
    float _m7;
    float _m8;
} _37;

layout(set = 0, binding = 0) uniform sampler2D _111;
layout(set = 0, binding = 2) uniform samplerBuffer _242;
layout(set = 0, binding = 1, rgb10_a2) uniform writeonly image2D _304;

void main()
{
    vec4 _361;
    if ((_37._m4 & 1u) != 0u)
    {
        float _60 = 0.0033333334140479564666748046875 * _37._m2;
        float _63 = float(gl_GlobalInvocationID.x);
        float _70 = float(gl_GlobalInvocationID.y);
        _361 = textureLod(_111, vec2(fma(fma(_63, _37._m1.x, sin(fma(_70 * _37._m1.y, 15.70794963836669921875, _37._m3)) * 0.0033333334140479564666748046875), 0.993333339691162109375, 0.0033333334140479564666748046875), fma(fma(_70, _37._m1.y, sin(fma(_63 * _37._m1.x, 15.70794963836669921875 * _37._m2, _37._m3)) * _60), fma(-_37._m2, 0.006666666828095912933349609375, 1.0), _60)), 0.0);
    }
    else
    {
        _361 = texelFetch(_111, ivec2(int(min(_37._m0.x, gl_GlobalInvocationID.x)), int(min(_37._m0.y, gl_GlobalInvocationID.y))), 0);
    }
    vec4 _364;
    if ((_37._m4 & 16u) != 0u)
    {
        uvec3 _148 = uvec3(_361.xyz * 255.0);
        uvec3 _315;
        _315 = uvec3(0u);
        uint _196;
        uvec3 _208;
        uint _210;
        vec4 _354;
        uint _316 = 7u;
        uint _317 = 0u;
        for (;;)
        {
            uvec3 _165 = uvec3(_316);
            uvec3 _166 = (_148 - _315) >> _165;
            uint _179 = (_166.x + (_166.y * 2u)) + (_166.z * 4u);
            _196 = _188._m0[_317]._m0[_179 / 4u][_179 % 4u];
            if (!((_196 & 2147483648u) == 0u))
            {
                uint _216 = _196 & 15u;
                uint _221 = (_196 >> uint(4)) & 65535u;
                int _318;
                vec3 _320;
                float _330;
                _330 = 9.9999996802856924650656260769173e+37;
                _320 = vec3(0.0);
                _318 = 0;
                uint _235;
                for (;;)
                {
                    _235 = uint(_318);
                    if (_235 < _216)
                    {
                        vec3 _251 = texelFetch(_242, int(_221 + _235)).xyz;
                        vec3 _256 = _361.xyz - _251;
                        float _261 = dot(_256, _256);
                        bool _264 = _261 < _330;
                        _330 = _264 ? _261 : _330;
                        _320 = mix(_320, _251, bvec3(_264));
                        _318++;
                        continue;
                    }
                    else
                    {
                        break;
                    }
                }
                vec4 _350 = _361;
                _350.x = _320.x;
                _350.y = _320.y;
                _350.z = _320.z;
                break;
            }
            _208 = _315 + (_166 << _165);
            _210 = _316 - 1u;
            _317 = _196;
            _316 = _210;
            _315 = _208;
            continue;
        }
        _364 = _350;
    }
    else
    {
        _364 = _361;
    }
    vec3 _295 = mix(_364.xyz, vec3(_37._m5, _37._m6, _37._m7), vec3(_37._m8));
    vec4 _356 = _364;
    _356.x = _295.x;
    _356.y = _295.y;
    _356.z = _295.z;
    imageStore(_304, ivec2(int(gl_GlobalInvocationID.x), int(gl_GlobalInvocationID.y)), _356);
}

End GLSL
```

Apparently, cross-compilation of a shader fails to produce correct code.

**Comment by Novum** [comment]
From what I can tell with tests of the latest spirv-cross it should work, I suspect MoltenVK just hasn't updated it.

**Comment by Novum** [comment]
What exact version of MoltenVK are you compiling against anyway?

**Comment by alexey-lysiuk** [comment]
I'm using [MoltenVK 1.1.10](https://github.com/KhronosGroup/MoltenVK/releases/tag/v1.1.10) which is the latest release at the moment. This version uses SPIRV-Cross at [the newest tag](https://github.com/KhronosGroup/SPIRV-Cross/releases/tag/sdk-1.3.216.0).

**Comment by robert-house** [comment]
I just wanted to chime in with my findings while waiting to see if an updated version of SPIRV-Cross fixes the particular shader issue. I did a quick port of the compile.sh script to ZSH so I could check to see if there are any differences in the shader output vs the version included in the Vulkan SDK for Mac. 

There are some pretty large differences in the sizes between either debug or release versions so the output IS different, however, I am running into an issue with segfaults that I am currently investigating. There are a few cases that are causing them and I'll list those here:

1. Compiling with DEBUG=1 with included pre-compiled shaders. Causes a segfault in GL_UpdateDescriptorSets. Related to the screen_effects_writes descriptor sets. I saw this before a few weeks back with a release build, but I didn't have the time/knowledge to investigate fully.
 
2. Compiling with RELEASE with self compiled shaders. 

3. Compiling with DEBUG=1 with self-compiled shaders. Segfaults in the same spot in DEBUG and I am assuming the same spot (line 1814) on release if I am reading lldb correctly.

I took a quick look through and some of the parameters are nullptr and for whatever reason, the validation layers do not want to enable for me on Mac. Once I figure out why this is the case, I'll dig further. 

As it stands, I think the shaders are being parsed in properly and the particular issue now is segfaulting on the screen_effect_writes descriptor set updates since I was seeing this same issue a few weeks back (and not the shader errors)

I can't make any promises since this is going to be a rather large learning curve for me to figure out what MoltenVK is doing, but maybe this will help point someone more knowledgeable in the right direction? Regardless, I'll keep digging and update my findings.

**Comment by Novum** [comment]
The shader has a pretty uncommon mix of descriptor types, including a uniform texel buffer. I wouldn't be surprised if that's very untested in MoltenVK.

**Comment by robert-house** [comment]
I haven't forgotten about this! I fixed the validation layers not loading for moltenvk and also went down the rabbit hole of fixing the no vulkan driver found on init. Should I open a PR for those issues?

As far as I can tell, when trying to allocate the screen effects descriptor set, VK_ERROR_OUT_OF_POOL_MEMORY is getting returned and since there are no checks, a null handle is returned causing the segfault. As to why this is the case, I am going to spend this week trying to figure out what is happening. In the mean time, I am going to add a check for results other than VK_SUCCESS and print an error to the console whenever this happens as a crash will probably follow.

As for the shader issues, they look like they are compiling to MSL just fine with only warnings about unused local vars. I will test on at least Linux to ensure I am not breaking anything before I open my PR. Maybe Windows if I have time to set up the VulkanSDK there too. Slow but steady progress!

**Comment by robert-house** [comment]
It is fixed :). I am going to clean up the mess I made, test that nothing is broken on windows/linux, and then I will open a pull reques
<img width="1392" alt="Screen Shot 2022-07-19 at 3 26 03 PM" src="https://user-images.githubusercontent.com/7016789/179858836-5c563ba7-c7e9-4757-8410-1e8838e3d4a3.png">
t

**Comment by Novum** [comment]
47e4b597ab2eeb54008d8a025b899ea88efebb0f
