### ISSUE TITLE
Build is broken on Linux

### ISSUE THREAD

**Issue by krishean** [Novum/vkQuake#303]
When attempting to build on Xubuntu 18.04 amd64 I get quite a few compile errors:

A fresh clone gives the following error:

```
cl_parse.c: At top level:
cl_parse.c:1495:13: error: static declaration of ‘CL_NewTranslation’ follows non-static declaration
 static void CL_NewTranslation (int slot)
             ^~~~~~~~~~~~~~~~~
In file included from quakedef.h:261:0,
                 from cl_parse.c:26:
client.h:373:6: note: previous declaration of ‘CL_NewTranslation’ was here
 void CL_NewTranslation (int slot);
      ^~~~~~~~~~~~~~~~~
Makefile:200: recipe for target 'cl_parse.o' failed
make: *** [cl_parse.o] Error 1
```

If I remove "static" from the function decleration I get the next error:

```
host.c:29:10: fatal error: windows.h: No such file or directory
 #include <windows.h>
          ^~~~~~~~~~~
compilation terminated.
Makefile:200: recipe for target 'host.o' failed
make: *** [host.o] Error 1
```

That include probably should at the very least be enclosed in a precompiler statement, commenting that out for simplicity's sake we get the next error:

```
cc strlcat.o strlcpy.o alias_frag.o alias_alphatest_frag.o alias_vert.o basic_alphatest_frag.o screen_warp_comp.o screen_warp_rgba8_comp.o cs_tex_warp_comp.o basic_frag.o basic_notex_frag.o basic_vert.o sky_layer_frag.o sky_layer_vert.o postprocess_frag.o postprocess_vert.o world_frag.o world_vert.o showtris_frag.o showtris_vert.o gl_refrag.o gl_rlight.o gl_rmain.o gl_fog.o gl_rmisc.o r_part.o r_world.o gl_screen.o gl_sky.o gl_warp.o gl_vidsdl.o gl_draw.o image.o gl_texmgr.o gl_mesh.o gl_heap.o r_sprite.o r_alias.o r_brush.o gl_model.o in_sdl.o snd_dma.o snd_mix.o snd_mem.o bgmusic.o snd_codec.o snd_flac.o snd_wave.o snd_vorbis.o snd_opus.o snd_mp3.o snd_mp3tag.o snd_mikmod.o snd_xmp.o snd_umx.o snd_sdl.o cd_sdl.o net_bsd.o net_udp.o net_dgrm.o net_loop.o net_main.o chase.o cl_demo.o cl_input.o cl_main.o cl_parse.o cl_tent.o console.o keys.o menu.o sbar.o view.o wad.o cmd.o common.o crc.o cvar.o cfgfile.o host.o host_cmd.o mathlib.o mdfour.o pr_cmds.o pr_edict.o pr_exec.o sv_main.o sv_move.o sv_phys.o sv_user.o world.o zone.o pl_linux.o sys_sdl_unix.o main_sdl.o   -lm -lX11-xcb -lvulkan   -lvorbisfile -lvorbis -logg -lmad -lSDL2 -o vkquake
sbar.o: In function `Sbar_CSQCCommand.part.0':
sbar.c:(.text+0x23): undefined reference to `PR_MakeTempString'
host.o: In function `_Host_Frame':
host.c:(.text+0x1601): undefined reference to `pr_checkextension'
pr_cmds.o:(.data.rel+0x0): undefined reference to `PF_Fixme'
pr_cmds.o:(.data.rel+0x18): undefined reference to `PF_Fixme'
pr_cmds.o:(.data.rel+0x28): undefined reference to `PF_Fixme'
pr_cmds.o:(.data.rel+0x40): undefined reference to `PF_Fixme'
pr_cmds.o:(.data.rel+0x88): undefined reference to `PF_Fixme'
pr_cmds.o:(.data.rel+0x98): more undefined references to `PF_Fixme' follow
pr_edict.o: In function `PR_ClearProgs':
pr_edict.c:(.text+0x3f3): undefined reference to `PR_ShutdownExtensions'
pr_edict.o: In function `PR_Init':
pr_edict.c:(.text+0x4f7): undefined reference to `PR_DumpPlatform_f'
pr_edict.o: In function `PR_LoadProgs':
pr_edict.c:(.text+0x3376): undefined reference to `PR_EnableExtensions'
pr_edict.o: In function `PR_Init':
pr_edict.c:(.text+0x595): undefined reference to `PR_InitExtensions'
sv_main.o: In function `SV_Init':
sv_main.c:(.text+0x1c9f): undefined reference to `pr_checkextension'
world.o: In function `SV_HullForEntity':
world.c:(.text+0x94a): undefined reference to `pr_checkextension'
world.o: In function `SV_LinkEdict':
world.c:(.text+0x1175): undefined reference to `pr_checkextension'
world.o: In function `SV_ClipMoveToEntity':
world.c:(.text+0x194b): undefined reference to `pr_checkextension'
world.o: In function `SV_Move':
world.c:(.text+0x2974): undefined reference to `pr_checkextension'
collect2: error: ld returned 1 exit status
Makefile:320: recipe for target 'vkquake' failed
make: *** [vkquake] Error 1
```

At this point I gave up and reverted the commits from the past two days because this is beyond me to fix with a few lines of sed in my build script. The project still builds on Linux as of the commits from Jun 10th.

I've tracked the errors to at least the following commits:
6f354a1599672b492ebed8291b822775ab90953c windows.h: No such file or directory
55a3bbced84c58134ff0497a741617b487dcf6f6 undefined reference to PF_Fixme
d9d4be488436c50afcc75b2aacdb50127f6546ab static declaration of ‘CL_NewTranslation’ follows non-static declaration

**Comment by Novum** [comment]
Okay. I don't understand why everybody expects top of tree to always compile? Compile the latest official release please.
