### ISSUE TITLE
Linux Build Failure/Regression - Undefined references in gl_rmisc.c

### ISSUE THREAD

**Issue by Kithop** [Novum/vkQuake#34]
Hi, just attempted to recompile with the lastest HEAD, failing with undefined references in gl_rmisc.c now (Ubuntu 16.04 64-bit).  Digging through the history for that file, though, this doesn't look like it's been touched specifically for a while.  I'll see if I can dig out a specific commit.

cc strlcat.o strlcpy.o gl_refrag.o gl_rlight.o gl_rmain.o gl_fog.o gl_rmisc.o r_part.o r_world.o gl_screen.o gl_sky.o gl_warp.o gl_vidsdl.o gl_draw.o image.o gl_texmgr.o gl_mesh.o r_sprite.o r_alias.o r_brush.o gl_model.o in_sdl.o snd_dma.o snd_mix.o snd_mem.o bgmusic.o snd_codec.o snd_flac.o snd_wave.o snd_vorbis.o snd_opus.o snd_mp3.o snd_mikmod.o snd_modplug.o snd_umx.o snd_sdl.o cd_sdl.o net_bsd.o net_udp.o net_dgrm.o net_loop.o net_main.o chase.o cl_demo.o cl_input.o cl_main.o cl_parse.o cl_tent.o console.o keys.o menu.o sbar.o view.o wad.o cmd.o common.o crc.o cvar.o cfgfile.o host.o host_cmd.o mathlib.o pr_cmds.o pr_edict.o pr_exec.o sv_main.o sv_move.o sv_phys.o sv_user.o world.o zone.o pl_linux.o sys_sdl_unix.o main_sdl.o  ../Shaders/Compiled/alias_frag.c ../Shaders/Compiled/alias_vert.c ../Shaders/Compiled/basic_alphatest_frag.c ../Shaders/Compiled/basic_frag.c ../Shaders/Compiled/basic_notex_frag.c ../Shaders/Compiled/basic_vert.c ../Shaders/Compiled/sky_layer_frag.c ../Shaders/Compiled/sky_layer_vert.c ../Shaders/Compiled/world_frag.c ../Shaders/Compiled/world_vert.c -L/lib -lm -l:libvulkan.so.1 -lX11-xcb   -lvorbisfile -lvorbis -logg -lmad -L/usr/lib/x86_64-linux-gnu -lSDL2 -o vkquake
gl_rmisc.o: In function `R_CreatePipelines':
gl_rmisc.c:(.text+0x1bcb): undefined reference to `postprocess_vert_spv_size'
gl_rmisc.c:(.text+0x1bd0): undefined reference to `postprocess_vert_spv'
gl_rmisc.c:(.text+0x1be0): undefined reference to `postprocess_frag_spv_size'
gl_rmisc.c:(.text+0x1be5): undefined reference to `postprocess_frag_spv'
collect2: error: ld returned 1 exit status
Makefile:307: recipe for target 'vkquake' failed
make: *** [vkquake] Error 1

**Comment by Kithop** [comment]
I've never done one before (hooray for learning!) but I just followed along figuring out how to do a git bisect, cleaning and re-making each time, and came up with this:

23a77706e44736a32080cb46257241a85b836be8 is the first bad commit
commit 23a77706e44736a32080cb46257241a85b836be8
Author: Axel Gneiting <mail@axelgneiting.de>
Date:   Sun Jul 31 19:26:09 2016 -0500

    Gamma postprocess

:040000 040000 de9e58ba9064b4a87947a2e8ac16608823337d78 1a0726ffc35b4f6cabd030f896744d66a38b4fe0 M	Quake
:040000 040000 96025c56293f4550665483c2ef30cc5d8805a328 5bada5378bfa60fda84550c25c4620ebb020e83e M	Shaders

**Comment by Kithop** [comment]
aaaaand it's fixed with 2e157a7

... I'm just pulling at the wrong time, it seems. ;) Thanks!

**Comment by calexil** [comment]
issue is back up

**Comment by sezero** [comment]
>  issue is back up

No, it is not. What you describe is https://github.com/Novum/vkQuake/issues/55
IIRC, you need at least 1.0.12.0 vulkan sdk to compile.

**Comment by mdeguzis** [comment]
This is also noted in the readme. This has been the case since 0.50
