### ISSUE TITLE
Failure to compile with GCC 12.1

### ISSUE THREAD

**Issue by bubbleguuum** [Novum/vkQuake#479]
Using master as of the date of this report.

Compilation fails on this, GCC 12.1, openSUSE Tumbleweed:

```
tasks.c: In function ‘Tasks_Init’:
tasks.c:297:55: error: writing 16 bytes into a region of size 0 [-Werror=stringop-overflow=]
  297 |                 steal_worker_indices[i + num_workers] = i;
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
tasks.c:87:24: note: at offset 64 into destination object ‘steal_worker_indices’ of size 64
   87 | static uint8_t         steal_worker_indices[MAX_WORKERS * 2];
```

**Comment by sezero** [comment]
This was initially discussed at https://github.com/Novum/vkQuake/issues/473

@Novum: Should I suppress this with the following?
```diff
diff --git a/Quake/tasks.c b/Quake/tasks.c
index e91f49e..7d06b48 100644
--- a/Quake/tasks.c
+++ b/Quake/tasks.c
@@ -290,12 +290,19 @@ void Tasks_Init (void)
 
 	num_workers = CLAMP (1, SDL_GetCPUCount (), MAX_WORKERS);
 
+#if defined(__GNUC__) && (__GNUC__ >= 10)
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wstringop-overflow"
+#endif
 	// Fill lookup table to avoid modulo in Task_ExecuteIndexed
 	for (int i = 0; i < num_workers; ++i)
 	{
 		steal_worker_indices[i] = i;
 		steal_worker_indices[i + num_workers] = i;
 	}
+#if defined(__GNUC__) && (__GNUC__ >= 10)
+#pragma GCC diagnostic pop
+#endif
 
 	indexed_task_counters = calloc (sizeof (task_counter_t) * num_workers * MAX_PENDING_TASKS, 1);
 	worker_threads = (SDL_Thread **)malloc (sizeof (SDL_Thread *) * num_workers);
```

**Comment by sezero** [comment]
Well, I tested a bit at https://godbolt.org, compiler seems to get
confused by the `CLAMP` macro, and the warning only happens at -O3
and not -O2.

Does the following quick patch fix the issue?

```diff
diff --git a/Quake/tasks.c b/Quake/tasks.c
index e91f49e..516a683 100644
--- a/Quake/tasks.c
+++ b/Quake/tasks.c
@@ -288,7 +288,9 @@ void Tasks_Init (void)
 		tasks[task_index].id_condition = SDL_CreateCond ();
 	}
 
-	num_workers = CLAMP (1, SDL_GetCPUCount (), MAX_WORKERS);
+	num_workers = SDL_GetCPUCount ();
+	if (num_workers > MAX_WORKERS) num_workers = MAX_WORKERS;
+	else if (num_workers < 1) num_workers = 1;
 
 	// Fill lookup table to avoid modulo in Task_ExecuteIndexed
 	for (int i = 0; i < num_workers; ++i)
```

**Comment by sezero** [comment]
Thinking about it, the compiler somehow was right to warn - that CLAMP macro is an abomination... Applied the patch and closed this. If there is still an issue, drop a note here.

**Comment by sezero** [comment]
@Novum, @andrei-drexler, @ericwa: There are other places where function
calls are used with `CLAMP`, `q_min` and `q_max` macros. One particularly
suspicious one is in `Fog_ParseServerMessage`:
https://github.com/Novum/vkQuake/blob/master/Quake/gl_fog.c#L103
... which may possibly lead to a second call to `MSG_ReadShort`. (I asked
metlslime about it at the [func board](https://celephais.net/board/view_thread.php?id=60452&start=3826). What do you guys think?

**Comment by Novum** [comment]
@sezero What exactly is the problem with the macro btw?

**Comment by sezero** [comment]
Which one?

**Comment by Novum** [comment]
Sorry I'm confused. Why is the macro an abomination exactly? At first glance it looks correct.

**Comment by Novum** [comment]
It's calling the function multiple times I guess?

**Comment by sezero** [comment]
Double evaluation of its args is the abomination: When you use a function call in it, it can be called double times, and the compiler most naturally doesn't know whether it will return the same value every time or not. Worse, multiple calls of a function argument can have unwanted side effects, e.g. the one in Fog_ParseServerMessage I noted above (which I don't know whether it was intentional and really doubt that it was.)

**Comment by sezero** [comment]
> It's calling the function multiple times I guess?

Yes. I'm preparing a patch for qs about it, will look at vkquake later unless you beat me to it.

**Comment by temx** [comment]
The macro explicitly forces two reads. Even more worryingly, the definition changed in 0.65; in 0.60 it's

```
		case svc_fog:
			Fog_Parse(MSG_ReadByte() / 255.0,
					  MSG_ReadByte() / 255.0,
					  MSG_ReadByte() / 255.0,
					  MSG_ReadByte() / 255.0,
					  max(0.0, MSG_ReadFloat()));
```

I don't think any engines produced `svc_fog` messages ever.  FTE can parse (not emit) the "current" version, but it'll read a single short.

Darkplaces can't parse it, its changelog (r1778) says "minor cleaning of obsolete protocol stuff (svc_fog is now considered unused, because it really never was used)".

**Comment by Novum** [comment]
@sezero f96aa07cbd136761b5dd1e00de88a46e3078bbce fixes this in a C11 way. You probably won't want to use that, but I think it's a good idea to prevent further errors.

**Comment by sezero** [comment]
> @sezero [f96aa07](https://github.com/Novum/vkQuake/commit/f96aa07cbd136761b5dd1e00de88a46e3078bbce) fixes this in a C11 way. 

Gcc seems happy in x64 mode, but for x86 it errors out, tried both gcc-4.9.4 and 7.5.0.
```
In file included from quakedef.h:258:0,
                 from gl_rmain.c:24:
gl_rmain.c: In function 'GL_FrustumMatrix':
common.h:61:2: error: '_Generic' specifies two compatible types
  size_t: q_min_size_t, \
  ^
gl_rmain.c:269:25: note: in expansion of macro 'q_min'
  const float d = 12.f * q_min (w, h);
                         ^~~~~
common.h:60:2: note: compatible type is here
  unsigned int: q_min_uint, \
  ^
gl_rmain.c:269:25: note: in expansion of macro 'q_min'
  const float d = 12.f * q_min (w, h);
                         ^~~~~
common.h:99:2: error: '_Generic' specifies two compatible types
  size_t: clamp_size_t, \
  ^
gl_rmain.c:270:18: note: in expansion of macro 'CLAMP'
  const float n = CLAMP (0.5f, d, NEARCLIP);
                  ^~~~~
common.h:98:2: note: compatible type is here
  unsigned int: clamp_uint, \
  ^
gl_rmain.c:270:18: note: in expansion of macro 'CLAMP'
  const float n = CLAMP (0.5f, d, NEARCLIP);
                  ^~~~~
In file included from quakedef.h:258:0,
                 from gl_rlight.c:24:
gl_rlight.c: In function 'RecursiveLightPoint':
common.h:61:2: error: '_Generic' specifies two compatible types
  size_t: q_min_size_t, \
  ^
gl_rlight.c:321:16: note: in expansion of macro 'q_min'
     *maxdist = q_min (*maxdist, dist);
                ^~~~~
common.h:60:2: note: compatible type is here
  unsigned int: q_min_uint, \
  ^
gl_rlight.c:321:16: note: in expansion of macro 'q_min'
     *maxdist = q_min (*maxdist, dist);
                ^~~~~
make: *** [Makefile.w32:182: gl_rlight.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile.w32:182: gl_rmain.o] Error 1
In file included from quakedef.h:258:0,
                 from gl_refrag.c:24:
gl_refrag.c: In function 'R_CheckEfrags':
common.h:80:2: error: '_Generic' specifies two compatible types
  size_t: q_max_size_t, \
  ^
gl_refrag.c:164:25: note: in expansion of macro 'q_max'
  dev_peakstats.efrags = q_max (cl.num_efrags, dev_peakstats.efrags);
                         ^~~~~
common.h:79:2: note: compatible type is here
  unsigned int: q_max_uint, \
  ^
gl_refrag.c:164:25: note: in expansion of macro 'q_max'
  dev_peakstats.efrags = q_max (cl.num_efrags, dev_peakstats.efrags);
                         ^~~~~
make: *** [Makefile.w32:182: gl_refrag.o] Error 1
```

**Comment by alexey-lysiuk** [comment]
32-bit MSVC target fails to compile [for the same reason](https://github.com/alexey-lysiuk/vkQuake/runs/6704319346?check_suite_focus=true#step:4:131).

**Comment by sezero** [comment]
Googling the error shows a few hits, this one possibly useful:
https://news.ycombinator.com/item?id=11882574

I'm not that good with c11, so a lazy solution would be not including `size_t`
in the `_Generic` list `#if !(defined(_LP64) || defined(_WIN64))` ??

**Comment by andrei-drexler** [comment]
I'd go with explicitly sized 32/64-bit ints/uints and not bother with smaller int types, something like
```c
// clang-format off
#define IMPL_Q_MIN(type, name) \
static inline type q_min_##name (type a, type b) \
{ \
	return (a < b) ? a : b; \
}
IMPL_Q_MIN (int32_t, int32_t)
IMPL_Q_MIN (uint32_t, uint32_t)
IMPL_Q_MIN (int64_t, int64_t)
IMPL_Q_MIN (uint64_t, uint64_t)
IMPL_Q_MIN (float, float)
IMPL_Q_MIN (double, double)
#define q_min(a, b) _Generic((a)+(b), \
	int32_t: q_min_int32_t, \
	uint32_t: q_min_uint32_t, \
	int64_t: q_min_int64_t, \
	uint64_t: q_min_uint64_t, \
	float: q_min_float, \
	double: q_min_double)(a, b)

#define IMPL_Q_MAX(type, name) \
static inline type q_max_##name (type a, type b) \
{ \
	return (a > b) ? a : b; \
}
IMPL_Q_MAX (int32_t, int32_t)
IMPL_Q_MAX (uint32_t, uint32_t)
IMPL_Q_MAX (int64_t, int64_t)
IMPL_Q_MAX (uint64_t, uint64_t)
IMPL_Q_MAX (float, float)
IMPL_Q_MAX (double, double)
#define q_max(a, b) _Generic((a)+(b), \
	int32_t: q_max_int32_t, \
	uint32_t: q_max_uint32_t, \
	int64_t: q_max_int64_t, \
	uint64_t: q_max_uint64_t, \
	float: q_max_float, \
	double: q_max_double)(a, b)

#define IMPL_CLAMP(type, name) \
static inline type clamp_##name (type minval, type val, type maxval) \
{ \
	return (val < minval) ? minval : ((val > maxval) ? maxval : val); \
}
IMPL_CLAMP (int32_t, int32_t)
IMPL_CLAMP (uint32_t, uint32_t)
IMPL_CLAMP (int64_t, int64_t)
IMPL_CLAMP (uint64_t, uint64_t)
IMPL_CLAMP (float, float)
IMPL_CLAMP (double, double)
#define CLAMP(minval, val, maxval) _Generic((val), \
	int32_t: clamp_int32_t, \
	uint32_t: clamp_uint32_t, \
	int64_t: clamp_int64_t, \
	uint64_t: clamp_uint64_t, \
	float: clamp_float, \
	double: clamp_double)(minval, val, maxval)
// clang-format on
```

**Comment by sezero** [comment]
Sounds better I think, but I'm not proficient with c11..

I pushed the following commits to qs to avoid the macro issues:
https://github.com/sezero/quakespasm/commit/284b182a1cf164538d6850fd751c1ed361093a74
https://github.com/sezero/quakespasm/commit/4c634688310653b85727b25c5bf714b474e5b0e9
https://github.com/sezero/quakespasm/commit/6c9bde021cba950f8ff840f3aff5e6b1a87605b0
https://github.com/sezero/quakespasm/commit/35b2d77661b3ada87d5721fbe7114631008480c2
https://github.com/sezero/quakespasm/commit/16d813859ff6522665a56dca93c3d902be91014e
https://github.com/sezero/quakespasm/commit/a82e3dd75ed13d439be1db3d6d312590bad5c7d1
