### ISSUE TITLE
does not compile on ubuntu 16.04

### ISSUE THREAD

**Issue by montvid** [Novum/vkQuake#87]
`~/vkQuake/Quake$ make
cc  -DNDEBUG -c -Wall -Wno-trigraphs  -O2 -std=gnu99 -fweb -frename-registers -I/include -DLINUX -DVK_USE_PLATFORM_XCB_KHR -DUSE_SDL2 -DUSE_CODEC_WAVE -DUSE_CODEC_VORBIS  -DUSE_CODEC_MP3 -I/usr/include/SDL2 -D_REENTRANT -o gl_vidsdl.o gl_vidsdl.c
In file included from /usr/include/string.h:630:0,
                 from q_stdinc.h:69,
                 from quakedef.h:49,
                 from gl_vidsdl.c:26:
gl_vidsdl.c: In function ‘GL_InitDevice’:
gl_vidsdl.c:685:15: error: ‘VK_EXT_DEBUG_MARKER_EXTENSION_NAME’ undeclared (first use in this function)
    if (strcmp(VK_EXT_DEBUG_MARKER_EXTENSION_NAME, device_extensions[i].extensio
               ^
gl_vidsdl.c:685:15: note: each undeclared identifier is reported only once for each function it appears in
gl_vidsdl.c:667:11: warning: variable ‘found_debug_marker_extension’ set but not used [-Wunused-but-set-variable]
  qboolean found_debug_marker_extension = false;
           ^
gl_vidsdl.c: At top level:
gl_vidsdl.c:245:17: warning: ‘VID_GetVSync’ defined but not used [-Wunused-function]
 static qboolean VID_GetVSync (void)
                 ^
Makefile:197: recipe for target 'gl_vidsdl.o' failed
make: *** [gl_vidsdl.o] Error 1
`

**Comment by mdeguzis** [comment]
The master tree builds just fine on a clean chroot of Ubuntu Xenial. Undefined references could indicate missing packages, or older packages.  It is more than likely you are using an older version of libvulkan-dev.  Per the [readme](https://github.com/Novum/vkQuake#linux), version 1.0.12.0 is required. Xenial has 1.0.8.0.

**Comment by montvid** [comment]
thank you, it compiles now. It is really hard to find the backport, thanks for the link.
